export const CELL_STATES = {
  EMPTY: 'empty',
  WALL: 'wall',
  START: 'start',
  END: 'end',
  VISITED: 'visited',
  PATH: 'path',
  FRONTIER: 'frontier',
};

export const ALGORITHMS = {
  ASTAR: 'astar',
  DIJKSTRA: 'dijkstra',
  BFS: 'bfs',
  DFS: 'dfs',
  GREEDY: 'greedy',
  BIDIRECTIONAL: 'bidirectional',
  JPS: 'jps',
  BIDIRECTIONAL_ASTAR: 'bidirectionalAStar',
  IDDFS: 'iddfs',
};

export const ALGORITHM_INFO = {
  [ALGORITHMS.ASTAR]: {
    name: 'A* Search',
    shortName: 'A*',
    description:
      'A* uses a heuristic function to guide its search toward the goal. It combines the actual cost from the start (g) with an estimated cost to the goal (h) to calculate f = g + h. This makes it both optimal and efficient.',
    howItWorks:
      'Like Dijkstra but smarter \u2014 the heuristic h(n) estimates distance to goal, so A* prioritizes nodes that look promising. As long as h(n) never overestimates (admissible heuristic), A* is guaranteed optimal while exploring far fewer nodes.',
    timeComplexity: 'O(E log V)',
    spaceComplexity: 'O(V)',
    weighted: true,
    guaranteesShortest: true,
    bestFor: 'General-purpose pathfinding when a heuristic is available. Used in games, robotics, and GPS navigation.',
    showsValues: true,
    pseudocode: [
      'function a_star(start, goal):',
      '  open = priority_queue(start, f = 0 + h(start))',
      '  g[start] = 0',
      '',
      '  while open is not empty:',
      '    current = open.pop()  // lowest f = g + h',
      '',
      '    if current == goal:',
      '      return reconstruct_path()',
      '',
      '    for each neighbor of current:',
      '      tentative_g = g[current] + cost(current, neighbor)',
      '      if tentative_g < g[neighbor]:',
      '        parent[neighbor] = current',
      '        g[neighbor] = tentative_g',
      '        f[neighbor] = tentative_g + h(neighbor)',
      '        open.add(neighbor, f[neighbor])',
      '',
      '  return no path found',
    ],
  },
  [ALGORITHMS.DIJKSTRA]: {
    name: "Dijkstra's Algorithm",
    shortName: 'Dijkstra',
    description:
      "Dijkstra's algorithm explores all directions equally, expanding outward from the start like a ripple in water. It always finds the shortest path by visiting nodes in order of their distance from the start.",
    howItWorks:
      'Treats every edge as equal cost and always picks the unvisited node closest to the start. It explores in perfect concentric waves \u2014 like dropping a stone in water. A* adds a heuristic to bias this toward the goal.',
    timeComplexity: 'O(E + V log V)',
    spaceComplexity: 'O(V)',
    weighted: true,
    guaranteesShortest: true,
    bestFor: 'Finding shortest paths in weighted graphs. The foundation of most pathfinding algorithms.',
    showsValues: true,
    pseudocode: [
      'function dijkstra(start, goal):',
      '  pq = priority_queue(start, dist = 0)',
      '  dist[start] = 0',
      '',
      '  while pq is not empty:',
      '    current = pq.pop()  // closest to start',
      '',
      '    if current == goal:',
      '      return reconstruct_path()',
      '',
      '    for each neighbor of current:',
      '      new_dist = dist[current] + cost(current, neighbor)',
      '      if new_dist < dist[neighbor]:',
      '        parent[neighbor] = current',
      '        dist[neighbor] = new_dist',
      '        pq.add(neighbor, new_dist)',
      '',
      '  return no path found',
    ],
  },
  [ALGORITHMS.BFS]: {
    name: 'Breadth-First Search',
    shortName: 'BFS',
    description:
      'BFS explores the grid layer by layer, visiting all neighbors at the current depth before moving deeper. It guarantees the shortest path in unweighted grids by exploring in a perfect square pattern.',
    howItWorks:
      'Uses a FIFO queue \u2014 first in, first out. Nodes discovered first are explored first, so it expands in uniform waves. Every node at distance d is visited before any node at distance d+1. This guarantees shortest path in unweighted graphs.',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    weighted: false,
    guaranteesShortest: true,
    bestFor: 'Unweighted grids. Simple, reliable, and guaranteed to find the shortest path when all edges have equal weight.',
    showsValues: false,
    pseudocode: [
      'function bfs(start, goal):',
      '  queue = [start]',
      '  visited[start] = true',
      '',
      '  while queue is not empty:',
      '    current = queue.shift()  // FIFO: first in, first out',
      '',
      '    if current == goal:',
      '      return reconstruct_path()',
      '',
      '    for each neighbor of current:',
      '      if not visited[neighbor] and not wall:',
      '        visited[neighbor] = true',
      '        parent[neighbor] = current',
      '        queue.push(neighbor)',
      '',
      '  return no path found',
    ],
  },
  [ALGORITHMS.DFS]: {
    name: 'Depth-First Search',
    shortName: 'DFS',
    description:
      'DFS dives as deep as possible along each branch before backtracking. It does NOT guarantee the shortest path \u2014 it may find a very long route while a shorter one exists. Included here to show why greedy depth exploration is often suboptimal.',
    howItWorks:
      'Uses recursion (or a LIFO stack) \u2014 always goes as deep as possible before trying alternatives. It may stumble on the goal through a very long detour while a short path exists nearby. Fast to find *a* path, but rarely the best one.',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    weighted: false,
    guaranteesShortest: false,
    bestFor: 'Maze generation and topological sorting. NOT recommended for shortest-path finding.',
    showsValues: false,
    pseudocode: [
      'function dfs(start, goal):',
      '  visited[start] = true',
      '',
      '  function explore(node):',
      '    if node == goal:',
      '      return true  // found!',
      '',
      '    for each neighbor of node:',
      '      if not visited[neighbor] and not wall:',
      '        visited[neighbor] = true',
      '        parent[neighbor] = node',
      '        if explore(neighbor):',
      '          return true',
      '        // backtrack: undo parent here',
      '',
      '    return false',
      '',
      '  explore(start)',
      '  return no path found',
    ],
  },
  [ALGORITHMS.GREEDY]: {
    name: 'Greedy Best-First Search',
    shortName: 'Greedy',
    description:
      'Greedy Best-First uses only the heuristic (estimated distance to goal) to decide which node to explore next. It races toward the goal but can be tricked into taking suboptimal paths because it ignores the actual cost traveled.',
    howItWorks:
      'Only looks at h(n) \u2014 the estimated distance to goal \u2014 and ignores g(n), the actual cost so far. Like navigating by just looking at the destination on the horizon while ignoring walls and detours. Fast but not optimal.',
    timeComplexity: 'O(E log V)',
    spaceComplexity: 'O(V)',
    weighted: true,
    guaranteesShortest: false,
    bestFor: 'When you need a "good enough" path quickly. Common in game AI where speed matters more than optimality.',
    showsValues: true,
    pseudocode: [
      'function greedy_best_first(start, goal):',
      '  open = priority_queue(start, h(start))',
      '',
      '  while open is not empty:',
      '    current = open.pop()  // lowest h only',
      '',
      '    if current == goal:',
      '      return reconstruct_path()',
      '',
      '    for each neighbor of current:',
      '      if not visited[neighbor] and not wall:',
      '        parent[neighbor] = current',
      '        h_val = heuristic(neighbor, goal)',
      '        open.add(neighbor, h_val)',
      '',
      '  return no path found',
      '',
      '  // note: f = h (no g component)',
      '  // fast but can miss optimal paths',
    ],
  },
  [ALGORITHMS.BIDIRECTIONAL]: {
    name: 'Bidirectional BFS',
    shortName: 'Bidirectional',
    description:
      'Runs two simultaneous BFS searches \u2014 one from the start and one from the end \u2014 meeting in the middle. This dramatically reduces the search space because each search only needs to cover half the distance.',
    howItWorks:
      'Two BFS waves expand toward each other. When they meet, stitch the two partial paths together. The search space drops from O(b^d) to O(2 \u00d7 b^(d/2)) \u2014 exponentially fewer nodes explored because each side only covers half the distance.',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    weighted: false,
    guaranteesShortest: true,
    bestFor: 'Large grids where searching from both ends is more efficient. Used in social networks and navigation systems.',
    showsValues: false,
    pseudocode: [
      'function bidirectional_bfs(start, goal):',
      '  queue_s = [start]     // from start',
      '  queue_e = [goal]      // from goal',
      '  visited_s = {start}',
      '  visited_e = {goal}',
      '',
      '  while both queues non-empty:',
      '    // expand one step from start side',
      '    current_s = queue_s.shift()',
      '    if visited_e contains current_s:',
      '      meeting_point = current_s',
      '      return stitch_paths()',
      '    for neighbor of current_s:',
      '      if not visited_s[neighbor]:',
      '        visited_s[neighbor] = true',
      '        queue_s.push(neighbor)',
      '',
      '    // expand one step from goal side',
      '    current_e = queue_e.shift()',
      '    if visited_s contains current_e:',
      '      meeting_point = current_e',
      '      return stitch_paths()',
      '    for neighbor of current_e:',
      '      if not visited_e[neighbor]:',
      '        visited_e[neighbor] = true',
      '        queue_e.push(neighbor)',
      '',
      '  return no path found',
    ],
  },
  [ALGORITHMS.JPS]: {
    name: 'Jump Point Search',
    shortName: 'JPS',
    description:
      'An optimization of A* that identifies "jump points" \u2014 strategically important nodes \u2014 and skips over uniform-cost regions. Dramatically fewer nodes are evaluated while still guaranteeing optimal paths on uniform grids.',
    howItWorks:
      'Builds on A* by "jumping" straight ahead in each direction until hitting a wall, the goal, or a "forced neighbor" (a wall beside the path that creates a detour). Only jump points get added to the open set, skipping thousands of redundant nodes.',
    timeComplexity: 'O(E log V)',
    spaceComplexity: 'O(V)',
    weighted: true,
    guaranteesShortest: true,
    bestFor: 'Large uniform grids. Up to 10x faster than A* by pruning redundant paths.',
    showsValues: true,
    pseudocode: [
      'function jump_point_search(start, goal):',
      '  // same as A* but uses jump() to prune',
      '  open = priority_queue(start, f = h(start))',
      '',
      '  while open is not empty:',
      '    current = open.pop()',
      '    if current == goal:',
      '      return reconstruct_path()',
      '',
      '    for each direction (dx, dy):',
      '      jp = jump(current, dx, dy, goal)',
      '      if jp exists and not visited:',
      '        g = dist(current, jp)',
      '        f = g + h(jp, goal)',
      '        open.add(jp, f)',
      '',
      'function jump(node, dx, dy, goal):',
      '  next = node + (dx, dy)',
      '  if next is wall: return null',
      '  if next == goal: return next',
      '  if has_forced_neighbor(next, dx, dy):',
      '    return next  // wall beside path',
      '  if dx != 0 and dy != 0:  // diagonal',
      '    if jump(next, dx, 0): return next',
      '    if jump(next, 0, dy): return next',
      '  return jump(next, dx, dy, goal)',
    ],
  },
  [ALGORITHMS.BIDIRECTIONAL_ASTAR]: {
    name: 'Bidirectional A*',
    shortName: 'Bi-A*',
    description:
      'Combines bidirectional search with A* heuristics \u2014 runs two A* searches simultaneously from start and end. Heuristics guide both searches toward each other, meeting faster than plain bidirectional BFS.',
    howItWorks:
      'Two A* searches with complementary heuristics: from start, h estimates distance to goal; from goal, h estimates distance to start. Both are guided toward each other. When they meet and neither side can improve the path, the optimal path is found.',
    timeComplexity: 'O(E log V)',
    spaceComplexity: 'O(V)',
    weighted: true,
    guaranteesShortest: true,
    bestFor: 'Large grids with clear line-of-sight. Best of both worlds: heuristic-guided and bidirectional.',
    showsValues: true,
    pseudocode: [
      'function bidirectional_astar(start, goal):',
      '  // two A* searches with opposite heuristics',
      '  open_s = queue(start, f = h(start, goal))',
      '  open_e = queue(goal, f = h(goal, start))',
      '  g_s[start] = 0,  g_e[goal] = 0',
      '',
      '  while both open sets non-empty:',
      '    // expand forward search',
      '    curr_s = open_s.pop()  // lowest f_s',
      '    for neighbor of curr_s:',
      '      if not visited_s[neighbor]:',
      '        g_s[neighbor] = g_s[curr_s] + 1',
      '        f = g_s[neighbor] + h(neighbor, goal)',
      '        open_s.add(neighbor, f)',
      '    if visited_e contains curr_s:',
      '      best = min(best, g_s[curr_s]+g_e[curr_s])',
      '',
      '    // expand backward search (mirror)',
      '    curr_e = open_e.pop()',
      '    ...same logic reversed...',
      '',
      '  return reconstruct_meeting_path()',
    ],
  },
  [ALGORITHMS.IDDFS]: {
    name: 'Iterative Deepening DFS',
    shortName: 'IDDFS',
    description:
      'Repeatedly runs depth-limited DFS with increasing depth limits. Combines DFS\'s low memory usage with BFS\'s guarantee of finding the shortest path. Explores in expanding waves from the start.',
    howItWorks:
      'Runs DFS with depth limit 0, then 1, then 2, etc. Each iteration re-explores shallower nodes, but since most nodes are at the deepest level, the overhead is small (constant factor ~2x). Gets BFS optimality with DFS memory usage.',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    weighted: false,
    guaranteesShortest: true,
    bestFor: 'Memory-constrained environments. Optimal like BFS but with linear memory.',
    showsValues: false,
    pseudocode: [
      'function iddfs(start, goal):',
      '  max_depth = rows + cols',
      '',
      '  for depth_limit = 0 to max_depth:',
      '    visited = empty  // reset each iteration',
      '    found = dfs_limit(start, goal, depth_limit)',
      '    if found:',
      '      return reconstruct_path()',
      '',
      '  return no path found',
      '',
      'function dfs_limit(node, goal, depth):',
      '  if depth == 0:',
      '    return node == goal',
      '  visited[node] = true',
      '  for each neighbor:',
      '    if not visited[neighbor] and not wall:',
      '      parent[neighbor] = node',
      '      if dfs_limit(neighbor, goal, depth-1):',
      '        return true',
      '      parent[neighbor] = null  // backtrack',
      '  return false',
      '',
      '  // re-explores shallow nodes many times,',
      '  // but most work is at the deepest level',
    ],
  },
};

export const MAZE_ALGORITHMS = {
  RECURSIVE_DIVISION: 'recursiveDivision',
  RECURSIVE_BACKTRACKER: 'recursiveBacktracker',
  RANDOM_WALLS: 'randomWalls',
};

export const MAZE_INFO = {
  [MAZE_ALGORITHMS.RECURSIVE_DIVISION]: {
    name: 'Recursive Division',
    description: 'Creates rooms with corridors by recursively dividing the grid with walls and passages.',
  },
  [MAZE_ALGORITHMS.RECURSIVE_BACKTRACKER]: {
    name: 'Recursive Backtracker',
    description: 'Carves passages using randomized DFS, creating perfect mazes with exactly one solution.',
  },
  [MAZE_ALGORITHMS.RANDOM_WALLS]: {
    name: 'Random Walls',
    description: 'Scatters walls randomly across the grid at configurable density.',
  },
};

export const SPEEDS = {
  CRAWL: { label: 'Crawl', delay: 200 },
  SLOW: { label: 'Slow', delay: 100 },
  NORMAL: { label: 'Normal', delay: 40 },
  FAST: { label: 'Fast', delay: 15 },
  TURBO: { label: 'Turbo', delay: 5 },
  INSTANT: { label: 'Instant', delay: 1 },
};

export const THEMES = {
  DARK: 'dark',
  LIGHT: 'light',
};

export const DIRECTIONS_4 = [
  [-1, 0],
  [1, 0],
  [0, -1],
  [0, 1],
];

export const DIRECTIONS_8 = [
  [-1, 0],
  [1, 0],
  [0, -1],
  [0, 1],
  [-1, -1],
  [-1, 1],
  [1, -1],
  [1, 1],
];

export const ALGORITHM_COLORS = {
  [ALGORITHMS.ASTAR]: {
    visited: 'bg-cyan-500',
    path: 'bg-cyan-300',
    label: 'text-cyan-400',
    dot: 'bg-cyan-400',
    hex: '#06B6D4',
    pathHex: '#67E8F9',
  },
  [ALGORITHMS.DIJKSTRA]: {
    visited: 'bg-violet-500',
    path: 'bg-violet-300',
    label: 'text-violet-400',
    dot: 'bg-violet-400',
    hex: '#8B5CF6',
    pathHex: '#C4B5FD',
  },
  [ALGORITHMS.BFS]: {
    visited: 'bg-emerald-500',
    path: 'bg-emerald-300',
    label: 'text-emerald-400',
    dot: 'bg-emerald-400',
    hex: '#10B981',
    pathHex: '#6EE7B7',
  },
  [ALGORITHMS.DFS]: {
    visited: 'bg-rose-500',
    path: 'bg-rose-300',
    label: 'text-rose-400',
    dot: 'bg-rose-400',
    hex: '#F43F5E',
    pathHex: '#FDA4AF',
  },
  [ALGORITHMS.GREEDY]: {
    visited: 'bg-amber-500',
    path: 'bg-amber-300',
    label: 'text-amber-400',
    dot: 'bg-amber-400',
    hex: '#F59E0B',
    pathHex: '#FCD34D',
  },
  [ALGORITHMS.BIDIRECTIONAL]: {
    visited: 'bg-blue-500',
    path: 'bg-blue-300',
    label: 'text-blue-400',
    dot: 'bg-blue-400',
    hex: '#3B82F6',
    pathHex: '#93C5FD',
  },
  [ALGORITHMS.JPS]: {
    visited: 'bg-fuchsia-500',
    path: 'bg-fuchsia-300',
    label: 'text-fuchsia-400',
    dot: 'bg-fuchsia-400',
    hex: '#D946EF',
    pathHex: '#F0ABFC',
  },
  [ALGORITHMS.BIDIRECTIONAL_ASTAR]: {
    visited: 'bg-teal-500',
    path: 'bg-teal-300',
    label: 'text-teal-400',
    dot: 'bg-teal-400',
    hex: '#14B8A6',
    pathHex: '#5EEAD4',
  },
  [ALGORITHMS.IDDFS]: {
    visited: 'bg-orange-500',
    path: 'bg-orange-300',
    label: 'text-orange-400',
    dot: 'bg-orange-400',
    hex: '#F97316',
    pathHex: '#FDBA74',
  },
};
